### PR TITLE
List runtime dependencies in getinline.gemspec

### PR DESCRIPTION
**Pull request by jeremyckahn**
@jv-dan @techn1cs As I understand it, this will cause client code of this library to install the dependencies upon running `bundle install`, correct?

@ShevaDas @pennetti @jabbowaki

### CODE REVIEW

**Comment by jabbowaki** [comment]
selfie-0
LGTM

**Comment by techn1cs** [comment]
Typically, in a custom gem there aren't even any entries in the core Gemfile. It's considered somewhat superfluous, and the expected dependencies/requirements are in .gemspec -- meaning I would remove the two deps you have in Gemfile. My $0.02

**Comment by jeremyckahn** [comment]
@techn1cs The reason I had to make this change was that `premailer` was not installed in the project that was using `getinline` as a dependency via `bundle install`.  Is there a better way to resolve this, or should the downstream project explicitly list `premailer` as a dependency alongside `getinline`?

**Comment by techn1cs** [comment]
@jeremyckahn You should be good with `premailer` (and any other required lib) so long as they are in the gemspec as a runtime dependency. In the including-project, bundler will catch that and add it to the list of what to install.

**Comment by techn1cs** [comment]
Nailed it! :shipit:

**Pull request merged**
